frr version 8.0
frr defaults traditional
hostname router1
!
router bgp 64500
 bgp router-id 10.100.0.11
 no bgp network import-check
 no bgp ebgp-requires-policy
 neighbor 10.100.0.12 remote-as 64501
 !
 address-family ipv4 unicast
  neighbor 10.100.0.12 activate
  network 203.0.113.0/24
 exit-address-family
!
line vty
