services:
  lb:
    image: nginx:1.25-alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: hashicorp/http-echo:1.0
    command: ["-text=response from backend1", "-listen=:5678"]

  backend2:
    image: hashicorp/http-echo:1.0
    command: ["-text=response from backend2", "-listen=:5678"]

  backend3:
    image: hashicorp/http-echo:1.0
    command: ["-text=response from backend3", "-listen=:5678"]
