worker_processes 1;    # см. упражнение 05 — с несколькими воркерами round-robin
                        # "ломается" на низком трафике, у каждого воркера свой счётчик

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
}
