upstream backend {
    least_conn;
    server backend1:5678 max_fails=2 fail_timeout=10s;
    server backend2:5678 max_fails=2 fail_timeout=10s;
    server backend3:5678 max_fails=2 fail_timeout=10s;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
    }

    location /healthz {
        return 200 "lb ok\n";
    }
}
