receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512

exporters:
  # Отправить traces в Jaeger
  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Экспортировать span metrics как Prometheus метрики
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Логировать в stdout (для отладки)
  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, logging]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
